App:
  RunMode: debug
  HttpPort: 8700
  ReadTimeout: 60
  WriteTimeout: 60
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: logs
  LogFileName: app
  LogFileExt: .log
  LinkPrefix: http://sc.vaiwan.com/ # 服务器所在域名
  RequestLimit: 1000 # 请求限制的时间间隔，单位毫秒
  NotFoundPage: http://oook.fun/404
  AllowOrigins:
    - http://localhost:8000

MongoDB:
  URI: mongodb://ok-short:123456@app.io:27017/ok-short
  DB: db_ok_short

Redis:
  Addr: 192.168.50.119:6379
  Password: ""
  DB: 0
