Server:
  RunMode: debug
  HttpPort: 8700
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: logs
  LogFileName: app
  LogFileExt: .log
  LinkPrefix: http://sc.vaiwan.com/ # 服务器所在域名
  RequestLimit: 1000 # 请求限制的时间间隔，单位毫秒
  NotFoundPage: http://oook.fun/404
MongoDB:
  User: ok-short
  Password: 123456
  AuthDB: ok-short
  Addr:
    192.168.50.20:27017
Redis:
  Addr: 192.168.50.20:6379
  Password: ""
  DB: 0
JWT:
  Secret: new_secret
  Issuer: ok-short
  Expire: 7200