Server:
  RunMode: debug
  HttpPort: 8700
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  LinkPrefix: http://sc.vaiwan.com/
Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: 127.0.0.1
  DBName: ok-short
  TablePrefix: ok_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
JWT:
  Secret: new_secret
  Issuer: ok-short
  Expire: 7200