Server:
  RunMode: debug
  HttpPort: 8700
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  LinkPrefix: http://sc.vaiwan.com/a/ # 服务器所在域名
Database:
  DBType: mysql
  UserName: pi172
  Password: 123456
  Host: 192.168.50.20
  DBName: ok-short
  TablePrefix: ok_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Addr: 192.168.50.20:6379
  Password: ""
  DB: 0
JWT:
  Secret: new_secret
  Issuer: ok-short
  Expire: 7200